### ISSUE TITLE
FastBreak does not work

### ISSUE THREAD

**Issue by personinblack** [joehot200/AntiAura#145]
```yaml
FastBreak:
  #Force kicks, even for OPs, if the blocks broken in a second is double the maximum?
  #Prevents people with bypass permission crashing the server with Nuker.
  ForceKicks: true
  #Accuracy-based detection is ALWAYS enabled in Survival mode.
  #Should accuracy-based FastBreak detection be enabled in Creative?
  AccuracyCreative: false
  #If this block can be broken in under this time, ignore FastBreak checks?
  #Time is in milliseconds. 500 = half a second.
  #Advanced config only.
  BreakSpeedIgnore: 1
  #Threshold for how many times user must be detected as hacking before the command executing.
  #Advanced config only.
  Threshold: 1
  #How much should the threshold of a player go down if the block broken was counted as legitimate?
  #Advanced config only.
  SafeHitDecrease: 0.0
  #Max blocks allowed to be broken in survival per second. Keep in mind that players could have highly-enchanted tools.
  #THIS WILL NOT BE DISABLED IF YOU HAVE THE CHECK DISABLED. THE ONLY WAY TO "DISABLE" THIS IS TO RAISE THIS VALUE.
  #Advanced config only.
  MaxSurvivalBlocksPerSecond: 1
  #Reset the amount of blocks broken upon teleport?
  #This can reduce false positives in specific scenarios, but can also be exploited by hackers.
  ResetUponTeleport: false
  #Max blocks allowed to be broken in creative per second.
  #THIS WILL NOT BE DISABLED IF YOU HAVE THE CHECK DISABLED. THE ONLY WAY TO "DISABLE" THIS IS TO RAISE THIS VALUE.
  #Advanced config only.
  MaxCreativeBlocksPerSecond: 40
  #Disable FastBreak when breaking tree logs?
  #Great for compatibility with plugins like ChopTree or similar.
  DisableFastBreakOnWood: false
  #Command to execute when FastBreak is detected?
  FastBreakCommand: # 
```

This configuration only triggers as `because they weren't looking at it` at too extreme speeds. Mining speed doesn't matter as long as you look at the block you are breaking.
